version: '3.8'
services:
  Jenkins:
    image: jenkins:jcasc
    privileged: true
    user: root
    restart: always
    environment:
      JENKINS_ADMIN_ID: "${JENKINS_ADMIN_ID}"
      JENKINS_ADMIN_PASSWORD: "${JENKINS_ADMIN_PASSWORD}"
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
       - /var/jenkins:/var/jenkins_home
       - ./casc_configs:/var/jenkins_conf
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf     